// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fhmzlodkwninmcwnothc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZobXpsb2Rrd25pbm1jd25vdGhjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkyMjkwMDAsImV4cCI6MjA3NDgwNTAwMH0.-dlCr-v-bCQTAIuu9N2cRqWqgBvdr3UFJuY4NMMu2QM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});